server:
  port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
    #禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:static/

  datasource:
    url: jdbc:h2:file:~/rx-middle-channel
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

    #    schema: classpath:db/schema.sql
    #    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
